# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/minisys-1a-cpu/minisys-1a-cpu.srcs/sources_1/ip/ins_rom_mem0/ins_rom_mem0.xci
# IP: The module: 'ins_rom_mem0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/minisys-1a-cpu/minisys-1a-cpu.srcs/sources_1/ip/ins_rom_mem0/ins_rom_mem0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ins_rom_mem0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/minisys-1a-cpu/minisys-1a-cpu.srcs/sources_1/ip/ins_rom_mem0/ins_rom_mem0.xci
# IP: The module: 'ins_rom_mem0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/minisys-1a-cpu/minisys-1a-cpu.srcs/sources_1/ip/ins_rom_mem0/ins_rom_mem0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ins_rom_mem0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
